### ISSUE TITLE
reconnect existing sessions broken on Connection Manager

### ISSUE THREAD

**Issue by xerothermic** [ajbalogh/ixnetwork_client_python#6]
Hi,

I'm testing ixnetwork_client_python with IxNetwork Connection Manager 8.40.1124.8 in GUI mode.
I was able to use the API to create a few sessions. However, when I tried to connect to existing sessions, I got a 404 error.

It turned out the Connection Manager does not like GET request /api/v1/sessions?links=true. If I manually issue _send_recv('GET', '/api/v1/sessions') then I could query a list of sessions in the Connection manager.

What is the best way to address this issue?

Patrick

**Comment by ajbalogh** [comment]
Connection Manager has a bug with its implementation of the query string param links=true on the sessions resource. There is a commit to address this. Connection Manager team will be notified of this problem.

**Comment by xerothermic** [comment]
Thanks for the quick update! Unfortunately, this commit b802907915db26d5519afb3d01ce759f15c11bb7 introduce another ?deprecated=true suffix, which makes self.get('/api/v1/sessions', links=False) still not working...

**Comment by ajbalogh** [comment]
Hi Patrick,

New version up that suppresses links and deprecated – give it a try and let me know.

Thanks
Andy
