### ISSUE TITLE
ixnet_object -> delete method not working in 8.50 EA

### ISSUE THREAD

**Issue by subha-py** [ajbalogh/ixnetwork_client_python#8]
Hi,
We use the delete method of IxnObject class,
which used to work perfectly in IxNetwork 8.40EA but now we are moving to IxNetwork 8.50EA and it is not working.

The following snippet should create an IxnObject instance and delete it.

```
w_topology = ixnhttp.root.create_child('topology')
w_topology.delete()
```
This is the traceback we are getting for 8.50EA
`Exception: 405 Method Not Allowed {"Message":"The requested resource does not support http method 'DELETE'."}`

Can you please look into it?

**Comment by ajbalogh** [comment]
scheme (http) will change on first 307 redirect to https

**Comment by subha-py** [comment]
Sorry didn't get the solution.
